-- Keep the Intel pipeline's historical render rows while letting new runs point
-- at editable Blank designs. Legacy rows continue using template_id/png_path;
-- new rows use the blank_* columns and leave the legacy artifact fields null.

alter table intel.art_renders
  add column if not exists blank_source_template_id text,
  add column if not exists blank_design_id text,
  add column if not exists edit_url text,
  add column if not exists png_url text;

-- New templates are canonical in public.templates, so they do not have an
-- intel.art_templates UUID. The existing FK still validates every non-null
-- legacy value.
alter table intel.art_renders
  alter column template_id drop not null;

-- n8n retries upsert the page generated by the same Blank design rather than
-- adding a duplicate tracking row.
create unique index if not exists art_renders_blank_design_page_uidx
  on intel.art_renders (blank_design_id, page);
